surface_segmentation:
  # Scene cropping
  crop_min_x: 0
  crop_max_x: 1.0
  crop_min_y: -0.65
  crop_max_y: 0.60
  crop_min_z: -0.5
  crop_max_z: 2.0
  
  # Plane detection
  horizontal_tolerance_degrees: 10.0
  margin_above_surface: 0.005
  # Multi-plane detection
  min_surface_size: 5000
  max_point_distance: 0.005
  
  # Clustering
  cluster_distance: 0.01
  min_cluster_size: 10
  max_cluster_size: 500 #10000
  
  # For downsampling saved point clouds
  vox_leaf_size: 0.01
